-- 2022년 3월의 오프라인/온라인 상품 판매 데이터 -> 판매 날짜, 상품 ID, 유저 ID, 판매량 
-- 오프라인 판매데이터 유저 ID는 널로 표시
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SUBSTR(SALES_DATE, 1, 7) = '2022-03'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SUBSTR(SALES_DATE, 1, 7) = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID