WITH RECURSIVE CTE (GENERATION, ID) AS (
SELECT 1, ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL

SELECT GENERATION+1, E.ID
FROM ECOLI_DATA E
JOIN CTE C ON E.PARENT_ID = C.ID)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (
SELECT PARENT_ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION